---
name: ci
on:
  pull_request:
jobs:
  ok:
    runs-on: ubuntu-24.04
    if: failure()
    needs:
      - test-lint
    steps:
      - run: exit 1
  test-lint:
    name: test and lint
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    env:
      AQUA_CONFIG: ${{ github.workspace }}/aqua.yaml
      AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        id: setup-go
        with:
          cache: true
          go-version: stable
      - run: go mod download
      - name: build
        run: |
          go build -o /dev/null ./...
      - name: test
        id: test
        continue-on-error: true
        run: |
          make clean coverage
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        if: ${{ steps.test.outcome == 'success' }}
      - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.43.3
      - run: aqua install
      - name: golangci-lint
        env:
          _go_version: ${{ steps.setup-go.outputs.go-version }}
        run: |
          golangci-lint run \
            --go "$_go_version" \
            --out-format line-number \
            --issues-exit-code 0 \
            --config .golangci.yml \
            1>lint-stdout.txt 2>/dev/stderr
      - name: reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          reviewdog \
            -name golangci-lint \
            -f golangci-lint \
            -filter-mode nofilter \
            -reporter github-pr-check \
            -fail-level error \
            < lint-stdout.txt
