---
name: release
on:
  push:
    branches:
      - main
jobs:
  tagpr:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: run tagpr
        run: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
